import { supabase } from "@/integrations/supabase/client";
import { pageAll } from "@/lib/fetch-all";

export type LedgerStatus = "active" | "inactive";

export type DuesRow = {
  student_id: string;
  full_name: string;
  mobile: string | null;
  roll_number: string | null;
  college_roll_number: string | null;
  unit_name: string | null;
  unit_id: string | null;
  sub_id: string | null;
  /** Active = no exit date set. Inactive = deactivated (exit date recorded). */
  status: LedgerStatus;
  joining_date: string | null;
  exit_date: string | null;
  last_payment_date: string | null;
  total_billed: number;
  paid: number;
  due_amount: number;
  opening_balance: number;
  adjustments: number;
  days_overdue: number;
};

const todayISO = () => new Date().toISOString().slice(0, 10);

/**
 * Single source of truth for the student ledger.
 * Due = Total Billed (monthly auto-billing rows) + Opening Balance + Adjustments − Payments received.
 * Billing rows are generated by the calendar-driven billing engine in the database,
 * never by payments.
 */
export async function fetchLedgerRows(planPrice: number): Promise<DuesRow[]> {
  void planPrice; // billing amounts always come from the generated billing rows
  const [studentsRes, subs, pays, adjs] = await Promise.all([
    pageAll<Record<string, unknown>>((from, to) =>
      supabase
        .from("students")
        .select(
          "id, full_name, mobile, roll_number, college_roll_number, unit_id, opening_balance, opening_balance_as_of, joining_date, exit_date, units(name)",
        )
        .range(from, to),
    ),

    pageAll<{ id: string; student_id: string; start_date: string; end_date: string; billed_amount: number | null }>(
      (from, to) => supabase.from("subscriptions").select("id, student_id, start_date, end_date, billed_amount").range(from, to),
    ),
    pageAll<{ student_id: string; amount: number; created_at: string }>((from, to) =>
      supabase
        .from("payments")
        .select("student_id, amount, created_at")
        .eq("status", "success")
        .order("created_at", { ascending: false })
        .range(from, to),
    ),
    pageAll<{ student_id: string; amount: number }>((from, to) =>
      supabase.from("ledger_adjustments").select("student_id, amount").range(from, to),
    ),
  ]);

  type St = {
    id: string; full_name: string; mobile: string | null; roll_number: string | null;
    college_roll_number: string | null; unit_id: string | null; opening_balance: number | null;
    opening_balance_as_of: string | null; joining_date: string | null; exit_date: string | null;
    units: { name: string } | null;
  };
  type Sub = { id: string; student_id: string; start_date: string; end_date: string; billed_amount: number | null };

  const students = studentsRes as unknown as St[];

  const subsByStudent = new Map<string, Sub[]>();
  for (const s of subs) {
    const arr = subsByStudent.get(s.student_id) ?? [];
    arr.push(s);
    subsByStudent.set(s.student_id, arr);
  }

  const adjByStudent = new Map<string, number>();
  for (const a of adjs) {
    adjByStudent.set(a.student_id, (adjByStudent.get(a.student_id) ?? 0) + Number(a.amount));
  }

  const paidByStudent = new Map<string, number>();
  const lastPayMap = new Map<string, string>();
  for (const p of pays) {
    paidByStudent.set(p.student_id, (paidByStudent.get(p.student_id) ?? 0) + Number(p.amount));
    if (!lastPayMap.has(p.student_id)) lastPayMap.set(p.student_id, p.created_at);
  }

  const today = todayISO();
  const rows: DuesRow[] = [];

  for (const st of students) {
    const stSubs = subsByStudent.get(st.id) ?? [];
    const opening = Number(st.opening_balance ?? 0);
    const adjustments = adjByStudent.get(st.id) ?? 0;
    const paid = paidByStudent.get(st.id) ?? 0;
    const subsBilled = stSubs.reduce((sum, sub) => sum + Number(sub.billed_amount ?? 0), 0);
    const totalBilled = subsBilled;
    const due = subsBilled + opening + adjustments - paid;

    const latest = stSubs.slice().sort((a, b) => (a.end_date > b.end_date ? -1 : 1))[0] ?? null;
    const lastPay = lastPayMap.get(st.id) ?? null;
    const refDate = lastPay
      ? lastPay.slice(0, 10)
      : (st.joining_date ?? latest?.start_date ?? st.opening_balance_as_of ?? today);
    const days = due > 0 ? Math.max(0, Math.floor((Date.parse(today) - Date.parse(refDate)) / 86400000)) : 0;

    rows.push({
      student_id: st.id,
      full_name: st.full_name,
      mobile: st.mobile,
      roll_number: st.roll_number,
      college_roll_number: st.college_roll_number,
      unit_name: st.units?.name ?? null,
      unit_id: st.unit_id,
      sub_id: latest?.id ?? null,
      status: st.exit_date ? "inactive" : "active",
      joining_date: st.joining_date,
      exit_date: st.exit_date,
      last_payment_date: lastPay,
      total_billed: totalBilled,
      paid,
      due_amount: due,
      opening_balance: opening,
      adjustments,
      days_overdue: days,
    });
  }

  rows.sort((a, b) => b.days_overdue - a.days_overdue);
  return rows;
}

/** Only students who currently owe money. */
export async function fetchDuesRows(planPrice: number): Promise<DuesRow[]> {
  return (await fetchLedgerRows(planPrice)).filter((r) => r.due_amount > 0);
}

export type StudentDueSummary = { due_amount: number; days_overdue: number };

/** Lightweight single-student due lookup (used by the attendance counter). */
export async function fetchStudentDue(studentId: string): Promise<StudentDueSummary> {
  const [stRes, subsRes, paysRes, adjRes] = await Promise.all([
    supabase
      .from("students")
      .select("opening_balance, opening_balance_as_of, joining_date")
      .eq("id", studentId)
      .maybeSingle(),
    supabase.from("subscriptions").select("start_date, billed_amount").eq("student_id", studentId),
    supabase
      .from("payments")
      .select("amount, created_at")
      .eq("student_id", studentId)
      .eq("status", "success")
      .order("created_at", { ascending: false }),
    supabase.from("ledger_adjustments").select("amount").eq("student_id", studentId),
  ]);

  const st = stRes.data as { opening_balance: number | null; opening_balance_as_of: string | null; joining_date: string | null } | null;
  const billed = (subsRes.data ?? []).reduce((s, r) => s + Number((r as { billed_amount: number | null }).billed_amount ?? 0), 0);
  const pays = (paysRes.data ?? []) as { amount: number; created_at: string }[];
  const paid = pays.reduce((s, p) => s + Number(p.amount), 0);
  const adjustments = (adjRes.data ?? []).reduce((s, a) => s + Number((a as { amount: number }).amount), 0);
  const due = billed + Number(st?.opening_balance ?? 0) + adjustments - paid;

  const today = todayISO();
  const firstSub = (subsRes.data ?? [])
    .map((s) => (s as { start_date: string }).start_date)
    .sort()[0];
  const refDate = pays[0]?.created_at.slice(0, 10) ?? st?.joining_date ?? firstSub ?? st?.opening_balance_as_of ?? today;
  const days = due > 0 ? Math.max(0, Math.floor((Date.parse(today) - Date.parse(refDate)) / 86400000)) : 0;

  return { due_amount: due, days_overdue: days };
}

